api/src/controllers/bookController/book.controller.js, api/src/models/User.js, api/src/routes/bookRoutes/book.route.js
agregue un GET de todas las reservas, modificando el archivo controller.books y el archivo routes.books
=> agregue un GET de todas las reservas

api/src/controllers/localControllers/local.controller.js, api/src/controllers/userControllers/user.controller.js, api/src/models/Book.js, api/src/models/Local.js
cada vez que se haga un get por Id al user y al local, te va adicionar los books asociados
=> update(api/src/controllers/localControllers/local.controller.js & src/controllers/userControllers/user.controller.js)

client/src/App.js, client/src/components/Details/Details.jsx, client/src/components/Details/details.module.css, client/src/components/FormBook/FormBook.jsx, client/src/redux/actions.js
Agregué validaciones al FormBook y un mensaje al usuario cuando se completa la reserva y antes de ser direccionado al home.
Rendericé el FormBook en el componente Detail y eliminé la ruta /booking del App
=> cambios y funcionalidad(Detail - FormBook - App)

client/src/components/Profile/Profile.jsx
=> agregue dependencias al useEffect de profile

api/src/controllers/localControllers/local.controller.js
Se arreglo un bug, cuando se buscaba por id no buscaba ningun local
=> fix(api/src/controllers/localControllers/local.controller.js)

client/src/components/FormBar/FormBar.jsx, client/src/components/Navbar/Navbar.jsx, client/src/redux/actions.js, client/src/redux/reducer.js
ya hice el boton logout en la nav bar con su handler, action y case en el reducer
=> Logout funcionando

api/src/controllers/bookController/book.controller.js, api/src/models/Book.js, client/src/components/Details/Details.jsx, client/src/components/FormBook/FormBook.jsx
se cambió allowNull a true en modelo Book - propiedad codeProm.
se quitó la verificación de las timestaps y codeProm en book.controller - postBookData
Se corrige el error del schedule en Detail para ver días y horas separados
Se corrige nombre de propiedades en FormBook para creacion de registro de reserva (people => personQuantity y date=>reservedDate)
=> fix(book.controller - Book - Detail - FormBook)

client/src/components/Details/Details.jsx, client/src/components/Details/details.module.css, client/src/components/FormBar/FormBar.jsx, client/src/components/FormBook/FormBook.jsx, client/src/components/Navbar/Navbar.jsx, client/src/components/SignUp/SignUp.jsx
Se quita la lupa del navbar y se hace que busque en tiempo real mientras se escribe en el input (corregir en el back que cuando se busca un local con un nombre que no existe los trae todos en lugar de ninguno)
Se aplican estilos del form signUp al form Book
=> cambios(Navbar Home - estilos FormBook)

client/src/components/FormsStyles/forms.module.css, client/src/components/Login/Login.jsx, client/src/components/SignUp/SignUp.jsx, client/src/index.css
cambios en inputs, botones, y centre todo
=> update css login y signup

client/src/components/FormBar/FormBar.jsx, client/src/components/FormBar/ValidationFormBar.jsx, client/src/components/FormBook/FormBook.jsx, client/src/components/FormsStyles/forms.module.css, client/src/components/SignUp/SignUp.jsx, client/src/components/SignUp/ValidationSignUp.jsx, client/src/redux/actions.js
Agregue validaciones en form de registro y creacion de bares, si se les ocurren cosas para validar diganme 
Ademas ya se puede agregar un local sin que haga falta marcar los checkbox de eventos y petFriendly
=> add(client/src/components/formBar & SignUp): agregue validaciones, etc

client/src/components/Profile/Profile.jsx, client/src/components/Profile/profile.module.css
se agrego mas estilos al componente profile y este ahora renderiza las reservas que los dueños de bares hagan a otros bares
=> update( /client/src/components/Profile/Profile.jsx) 

client/src/components/Navbar/navbar.module.css, client/src/index.css
=> fix(client/components/index.css): saque subrayado a los links

api/src/models/Book.js, client/src/App.js, client/src/components/FormBar/FormBar.jsx, client/src/components/FormBook/FormBook.jsx, client/src/components/Profile/Profile.jsx, client/src/redux/actions.js
1) no se hacian las reservas porque no se le pasaba el userId y por algo mas q no me acuerdo (ya se hacen)
2) cuando hacias click en reservar se renderizaba un mensaje que decia “successfull booking” pero se renderizaba aunque la reserva no se haya hecho. Ya agregue manejo de errores asi que  te redirecciona a tu perfil y sino muestra una alerta con el error.
3) en profile: 
• si eras cliente renderizaba solo un titulo de “tus reservas” pero sin nada
• si tenias locales te renderizaba tus locales Y tus reservas pero:  no mostraba el nombre del local, y la fecha aparecia con un horario (porque en el modelo de book la fecha era tipo date, pero la cambiamos a date only)
4) borre varias lineas vacias x toc je
=> arreglamos problemas con reservas

client/src/components/Details/Details.jsx, client/src/components/FormBook/FormBook.jsx, client/src/components/Navbar/navbar.module.css, client/src/components/Profile/Profile.jsx
se agregó subrayado en el hover del dropdown de profile
se solucionó la dirección a login desde FormBook si no se está logueado
se agregó boton de volver (a detalles) desde el formBook
=> fix(FormBook)

client/src/components/Profile/Profile.jsx, client/src/components/SignUp/SignUp.jsx
=> Update google auth

client/src/components/Login/Login.jsx, client/src/components/Profile/Profile.jsx, client/src/components/SignUp/SignUp.jsx, package.json
ahora cuando te registres se te enviara un email con tu contraseña
=> update(client/src/components/SignUp/SignUp.jsx ) 

client/src/components/FormBook/FormBook.jsx
se arreglo el bug del boton de reserva
=> fix(client/src/components/FormBook/FormBook.jsx) 

api/src/controllers/bulkController/bulk.controller.js, api/src/controllers/mercadoPagoController/mercadoPago.controller.js, client/src/components/FormBook/FormBook.jsx, client/src/components/MyBookInfo/myBookInfo.jsx, client/src/components/MyBookInfo/myBookInfo.module.css
se agrego una validacion cuando el pago es rechzado
=> úpdate(client/src/components/MyBookInfo/myBookInfo.jsx) 

client/src/components/EditLocal/editLocal.module.css, client/src/components/FormBar/FormBar.module.css, client/src/components/FormsStyles/forms.module.css, client/src/components/MyBookInfo/myBookInfo.jsx, client/src/components/MyBookInfo/myBookInfo.module.css, client/src/components/MyLocalsInfo/LocalsInfo.jsx, client/src/components/MyLocalsInfo/localsInfo.module.css, client/src/components/Profile/Profile.jsx, client/src/components/Profile/profile.module.css, client/src/components/UserInfo/UserInfo.jsx, client/src/components/UserInfo/userInfo.module.css
Primeros estilos. Todavia me falta terminar la parte del detalle y edicion de los locales, pero sigo mañana.
=> estilos profile (parte 1)

api/src/routes/localRoutes/local.route.js, client/src/components/DashboardAdmin.jsx/Dashboard.jsx, client/src/redux/actions.js
=> Reject request

client/src/App.js, client/src/components/BarOwnerPanel/BarOwnerPanel.jsx, client/src/components/Card/card.module.css, client/src/components/Profile/Profile.jsx, client/src/components/Profile/profile.module.css
tmb le puse sombra a las cards.
El componente ya esta conectado con el profile
=> nuevo componente para duenos de bares 

client/src/components/BarOwnerPanel/BarOwnerPanel.jsx, client/src/components/BarOwnerPanel/BarOwnerPanel.module.css, client/src/components/MyLocalsInfo/LocalsInfo.jsx, client/src/components/MyLocalsInfo/localsInfo.module.css, client/src/components/Navbar/Navbar.jsx, client/src/components/ShowLocalInfo/ShowLocalInfo.jsx, client/src/components/ShowLocalInfo/showLocalInfo.module.css
lo conectamos a la navbar + algo de estilos
=> avances en ownerBar panel

client/src/App.js, client/src/components/Login/Login.jsx, client/src/components/Password/Password.jsx, client/src/redux/actions.js, client/src/redux/reducer.js
Ya puedes recuperar tu contraseña el mensaje llegara al correo, del login se eliminaron console.log
=> update(client/src/components/Password/Password.jsx & client/src/components/Login/Login.jsx)

client/src/components/FormBook/FormBook.jsx, client/src/components/Password/Password.jsx, client/src/redux/actions.js
Cuando se hace la reserva se envia notificacion al correo
[update(client/src/components/Password/Password.jsx)se crea validacion a la hora de recuperar la contraseña
=> uddate(client/src/components/FormBook/FormBook.jsx & client/src/components/Password/Password.jsx)

client/src/components/BarOwnerPanel/BarOwnerPanel.module.css, client/src/components/Card/card.module.css, client/src/components/Home/Home.jsx, client/src/components/Home/home.module.css, client/src/components/MyLocalsInfo/localsInfo.module.css, client/src/components/Navbar/navbar.module.css, client/src/components/Profile/profile.module.css, client/src/components/ShowLocalInfo/showLocalInfo.module.css
update(home/ & localsinf/ navbar/ porfile/showlocal) 
se le dio responsive a estos modulos tanto en el modo oscuro como en el modo claro
=> update(home/ & localsinf/ navbar/ porfile/showlocal) 

client/src/components/Card/card.module.css, client/src/components/FormBar/FormBar.module.css, client/src/components/FormsStyles/forms.module.css
se agrego responsive al modulo formBar
=> update(client/src/components/FormBar/FormBar.module.css) se agrego re…   …sponsive al modulo formBar

api/src/controllers/bulkController/bulk.controller.js, client/src/components/Details/details.module.css, client/src/components/FormBook/FormBook.jsx, client/src/components/MyBookInfo/myBookInfo.module.css, client/src/components/Password/Password.jsx
se agrego resposive al componente Details, y se mejoro los otros componentes en la parte del reponsive
=> update(Details/ FormBook/ MyBookInfo/ Password) 

client/src/components/Details/Details.jsx, client/src/components/MyBookInfo/myBookInfo.jsx, client/src/components/Profile/Profile.jsx, client/src/redux/store.js
=> fix put rating

client/src/components/Home/home.module.css, client/src/components/Navbar/Navbar.jsx, client/src/components/Navbar/navbar.module.css, client/src/components/ScrollUpButton/ScrollUpButton.module.css
en la compu las opciones se ven en la navbar, en el celu se ven dentro de un menu hamburguesa
=> NavBar nueva

client/src/components/BarOwnerPanel/BarOwnerPanel.jsx, client/src/components/BarOwnerPanel/BarOwnerPanel.module.css, client/src/components/Card/card.module.css, client/src/components/DashboardAdmin.jsx/Dashboard.jsx, client/src/components/DashboardAdmin.jsx/Dashboard.module.css, client/src/components/FormsStyles/forms.module.css, client/src/components/Home/home.module.css, client/src/components/MyLocalsInfo/localsInfo.module.css, client/src/components/Navbar/Navbar.jsx, client/src/components/Navbar/navbar.module.css, client/src/components/Profile/Profile.jsx, client/src/components/ScrollUpButton/ScrollUpButton.module.css
cambios de estilos 
darkmode
responsive
etc
=> Dashboard admin
